/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.DataOutputStream;
import java.io.EOFException;
import java.io.IOException;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author carla
 */
public class Panel extends javax.swing.JFrame implements MouseListener {

    ArrayList<JLabel> labels = new ArrayList();
    ArrayList<JLabel> seleccionados = new ArrayList();
    ArrayList<Integer> numeros = new ArrayList();
    Socket socket = null;
    Connection conexion;
    private static Panel panel = null;
    private final String miIp;

    private Panel() {
        initComponents();
        conexion = new Connection();
        numeros = conexion.saludarServer();
        llenarLabels();
        crearEventos();
        iniciarMulticast();
        miIp = conexion.getMiIp();

    }

    public static Panel getInstance() {
        if (panel == null) {
            panel = new Panel();
        }
        return panel;
    }

    public final void llenarLabels() {
        labels.add(T1);
        labels.add(T2);
        labels.add(T3);
        labels.add(T4);
        labels.add(T5);
        labels.add(T6);
        labels.add(T7);
        labels.add(T8);
        labels.add(T9);
        labels.add(T10);
        labels.add(T11);
        labels.add(T12);
        labels.add(T13);
        labels.add(T14);
        labels.add(T15);
        labels.add(T16);
        labels.add(T17);
        labels.add(T18);
        labels.add(T19);
        labels.add(T20);
        labels.add(T21);
        labels.add(T22);
        labels.add(T23);
        labels.add(T24);
        labels.add(T25);
        labels.add(T26);
        labels.add(T27);
        labels.add(T28);
        labels.add(T29);
        labels.add(T30);
        labels.add(T31);
        labels.add(T32);
        labels.add(T33);
        labels.add(T34);
        labels.add(T35);
        labels.add(T36);
        labels.add(T37);
        labels.add(T38);
        labels.add(T39);
        labels.add(T40);
        labels.add(T41);
        labels.add(T42);
        labels.add(T43);
        labels.add(T44);
        labels.add(T45);
        labels.add(T46);
        labels.add(T47);
        labels.add(T48);
        labels.add(T49);
        labels.add(T50);
        labels.add(T51);
        labels.add(T52);
        labels.add(T53);
        labels.add(T54);
        labels.add(T55);
        labels.add(T56);
        labels.add(T57);
        labels.add(T58);
        labels.add(T59);
        labels.add(T60);
        labels.add(T61);
        labels.add(T62);
        labels.add(T63);
        labels.add(T64);
        labels.add(T65);
        labels.add(T66);
        labels.add(T67);
        labels.add(T68);
        labels.add(T69);
        labels.add(T70);
        labels.add(T71);
        labels.add(T72);
        labels.add(T73);
        labels.add(T74);
        labels.add(T75);
        labels.add(T76);
        labels.add(T77);
        labels.add(T78);
        labels.add(T79);
        labels.add(T80);
        labels.add(T81);
        labels.add(T82);
        labels.add(T83);
        labels.add(T84);
        labels.add(T85);
        labels.add(T86);
        labels.add(T87);
        labels.add(T88);
        labels.add(T89);
        labels.add(T90);
        labels.add(T91);
        labels.add(T92);
        labels.add(T93);
        labels.add(T94);
        labels.add(T95);
        labels.add(T96);
        labels.add(T97);
        labels.add(T98);
        labels.add(T99);
        labels.add(T100);
        asignarTarjetas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        T1 = new javax.swing.JLabel();
        T2 = new javax.swing.JLabel();
        T3 = new javax.swing.JLabel();
        T4 = new javax.swing.JLabel();
        T5 = new javax.swing.JLabel();
        T6 = new javax.swing.JLabel();
        T7 = new javax.swing.JLabel();
        T8 = new javax.swing.JLabel();
        T9 = new javax.swing.JLabel();
        T10 = new javax.swing.JLabel();
        T11 = new javax.swing.JLabel();
        T12 = new javax.swing.JLabel();
        T13 = new javax.swing.JLabel();
        T14 = new javax.swing.JLabel();
        T15 = new javax.swing.JLabel();
        T16 = new javax.swing.JLabel();
        T17 = new javax.swing.JLabel();
        T18 = new javax.swing.JLabel();
        T19 = new javax.swing.JLabel();
        T20 = new javax.swing.JLabel();
        T21 = new javax.swing.JLabel();
        T22 = new javax.swing.JLabel();
        T23 = new javax.swing.JLabel();
        T24 = new javax.swing.JLabel();
        T25 = new javax.swing.JLabel();
        T26 = new javax.swing.JLabel();
        T27 = new javax.swing.JLabel();
        T28 = new javax.swing.JLabel();
        T29 = new javax.swing.JLabel();
        T30 = new javax.swing.JLabel();
        T31 = new javax.swing.JLabel();
        T32 = new javax.swing.JLabel();
        T33 = new javax.swing.JLabel();
        T34 = new javax.swing.JLabel();
        T35 = new javax.swing.JLabel();
        T36 = new javax.swing.JLabel();
        T37 = new javax.swing.JLabel();
        T38 = new javax.swing.JLabel();
        T39 = new javax.swing.JLabel();
        T40 = new javax.swing.JLabel();
        T41 = new javax.swing.JLabel();
        T42 = new javax.swing.JLabel();
        T43 = new javax.swing.JLabel();
        T44 = new javax.swing.JLabel();
        T45 = new javax.swing.JLabel();
        T46 = new javax.swing.JLabel();
        T47 = new javax.swing.JLabel();
        T48 = new javax.swing.JLabel();
        T49 = new javax.swing.JLabel();
        T50 = new javax.swing.JLabel();
        T51 = new javax.swing.JLabel();
        T52 = new javax.swing.JLabel();
        T53 = new javax.swing.JLabel();
        T54 = new javax.swing.JLabel();
        T55 = new javax.swing.JLabel();
        T56 = new javax.swing.JLabel();
        T57 = new javax.swing.JLabel();
        T58 = new javax.swing.JLabel();
        T59 = new javax.swing.JLabel();
        T60 = new javax.swing.JLabel();
        T61 = new javax.swing.JLabel();
        T62 = new javax.swing.JLabel();
        T63 = new javax.swing.JLabel();
        T64 = new javax.swing.JLabel();
        T65 = new javax.swing.JLabel();
        T66 = new javax.swing.JLabel();
        T67 = new javax.swing.JLabel();
        T68 = new javax.swing.JLabel();
        T69 = new javax.swing.JLabel();
        T70 = new javax.swing.JLabel();
        T71 = new javax.swing.JLabel();
        T72 = new javax.swing.JLabel();
        T73 = new javax.swing.JLabel();
        T74 = new javax.swing.JLabel();
        T75 = new javax.swing.JLabel();
        T76 = new javax.swing.JLabel();
        T77 = new javax.swing.JLabel();
        T78 = new javax.swing.JLabel();
        T79 = new javax.swing.JLabel();
        T80 = new javax.swing.JLabel();
        T81 = new javax.swing.JLabel();
        T82 = new javax.swing.JLabel();
        T83 = new javax.swing.JLabel();
        T84 = new javax.swing.JLabel();
        T85 = new javax.swing.JLabel();
        T86 = new javax.swing.JLabel();
        T87 = new javax.swing.JLabel();
        T88 = new javax.swing.JLabel();
        T89 = new javax.swing.JLabel();
        T90 = new javax.swing.JLabel();
        T91 = new javax.swing.JLabel();
        T92 = new javax.swing.JLabel();
        T93 = new javax.swing.JLabel();
        T94 = new javax.swing.JLabel();
        T95 = new javax.swing.JLabel();
        T96 = new javax.swing.JLabel();
        T97 = new javax.swing.JLabel();
        T98 = new javax.swing.JLabel();
        T99 = new javax.swing.JLabel();
        T100 = new javax.swing.JLabel();
        btnMezclar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        J1 = new javax.swing.JLabel();
        J2 = new javax.swing.JLabel();
        J3 = new javax.swing.JLabel();
        J4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Memorama");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(65, 72, 80));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        T1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/1.png"))); // NOI18N
        T1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T1.setEnabled(false);

        T2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/2.png"))); // NOI18N
        T2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T2.setEnabled(false);

        T3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T3.setEnabled(false);

        T4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T4.setEnabled(false);

        T5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T5.setEnabled(false);

        T6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T6.setEnabled(false);

        T7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T7.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T7.setEnabled(false);

        T8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T8.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T8.setEnabled(false);

        T9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T9.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T9.setEnabled(false);

        T10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T10.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T10.setEnabled(false);

        T11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T11.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T11.setEnabled(false);

        T12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T12.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T12.setEnabled(false);

        T13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T13.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T13.setEnabled(false);

        T14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T14.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T14.setEnabled(false);

        T15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T15.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T15.setEnabled(false);

        T16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T16.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T16.setEnabled(false);

        T17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T17.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T17.setEnabled(false);

        T18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T18.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T18.setEnabled(false);

        T19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T19.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T19.setEnabled(false);

        T20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T20.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T20.setEnabled(false);

        T21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T21.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T21.setEnabled(false);

        T22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T22.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T22.setEnabled(false);

        T23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T23.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T23.setEnabled(false);

        T24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T24.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T24.setEnabled(false);

        T25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T25.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T25.setEnabled(false);

        T26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T26.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T26.setEnabled(false);

        T27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T27.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T27.setEnabled(false);

        T28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T28.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T28.setEnabled(false);

        T29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T29.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T29.setEnabled(false);

        T30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T30.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T30.setEnabled(false);

        T31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T31.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T31.setEnabled(false);

        T32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T32.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T32.setEnabled(false);

        T33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T33.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T33.setEnabled(false);

        T34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T34.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T34.setEnabled(false);

        T35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T35.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T35.setEnabled(false);

        T36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T36.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T36.setEnabled(false);

        T37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T37.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T37.setEnabled(false);

        T38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T38.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T38.setEnabled(false);

        T39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T39.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T39.setEnabled(false);

        T40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T40.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T40.setEnabled(false);

        T41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T41.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T41.setEnabled(false);

        T42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T42.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T42.setEnabled(false);

        T43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T43.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T43.setEnabled(false);

        T44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T44.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T44.setEnabled(false);

        T45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T45.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T45.setEnabled(false);

        T46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T46.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T46.setEnabled(false);

        T47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T47.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T47.setEnabled(false);

        T48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T48.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T48.setEnabled(false);

        T49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T49.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T49.setEnabled(false);

        T50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T50.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T50.setEnabled(false);

        T51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T51.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T51.setEnabled(false);

        T52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T52.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T52.setEnabled(false);

        T53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T53.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T53.setEnabled(false);

        T54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T54.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T54.setEnabled(false);

        T55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T55.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T55.setEnabled(false);

        T56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T56.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T56.setEnabled(false);

        T57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T57.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T57.setEnabled(false);

        T58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T58.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T58.setEnabled(false);

        T59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T59.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T59.setEnabled(false);

        T60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T60.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T60.setEnabled(false);

        T61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T61.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T61.setEnabled(false);

        T62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T62.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T62.setEnabled(false);

        T63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T63.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T63.setEnabled(false);

        T64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T64.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T64.setEnabled(false);

        T65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T65.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T65.setEnabled(false);

        T66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T66.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T66.setEnabled(false);

        T67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T67.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T67.setEnabled(false);

        T68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T68.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T68.setEnabled(false);

        T69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T69.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T69.setEnabled(false);

        T70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T70.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T70.setEnabled(false);

        T71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T71.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T71.setEnabled(false);

        T72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T72.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T72.setEnabled(false);

        T73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T73.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T73.setEnabled(false);

        T74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T74.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T74.setEnabled(false);

        T75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T75.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T75.setEnabled(false);

        T76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T76.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T76.setEnabled(false);

        T77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T77.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T77.setEnabled(false);

        T78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T78.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T78.setEnabled(false);

        T79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T79.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T79.setEnabled(false);

        T80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T80.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T80.setEnabled(false);

        T81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T81.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T81.setEnabled(false);

        T82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T82.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T82.setEnabled(false);

        T83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T83.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T83.setEnabled(false);

        T84.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T84.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T84.setEnabled(false);

        T85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T85.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T85.setEnabled(false);

        T86.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T86.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T86.setEnabled(false);

        T87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T87.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T87.setEnabled(false);

        T88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T88.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T88.setEnabled(false);

        T89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T89.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T89.setEnabled(false);

        T90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T90.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T90.setEnabled(false);

        T91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T91.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T91.setEnabled(false);

        T92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T92.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T92.setEnabled(false);

        T93.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T93.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T93.setEnabled(false);

        T94.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T94.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T94.setEnabled(false);

        T95.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T95.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T95.setEnabled(false);

        T96.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T96.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T96.setEnabled(false);

        T97.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T97.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T97.setEnabled(false);

        T98.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T98.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T98.setEnabled(false);

        T99.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T99.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T99.setEnabled(false);

        T100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T100.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0.png"))); // NOI18N
        T100.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(T1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(T11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(T21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(T31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(T41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(T51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T56)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T57)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T58)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T59)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T60))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(T61)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T62)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T63)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T64)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T65)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T66)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T67)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T68)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T69)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T70))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(T71)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T72)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T73)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T74)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T75)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T76)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T77)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T78)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T79)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(T81)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T82)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T83)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T84)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T85)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T86)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T87)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T88)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T89)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T90))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(T91)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T92)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T93)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T94)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T95)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T96)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T97)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T98)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T99)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T1)
                    .addComponent(T2)
                    .addComponent(T3)
                    .addComponent(T4)
                    .addComponent(T5)
                    .addComponent(T6)
                    .addComponent(T7)
                    .addComponent(T8)
                    .addComponent(T9)
                    .addComponent(T10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T11)
                    .addComponent(T12)
                    .addComponent(T13)
                    .addComponent(T14)
                    .addComponent(T15)
                    .addComponent(T16)
                    .addComponent(T17)
                    .addComponent(T18)
                    .addComponent(T19)
                    .addComponent(T20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(T21)
                    .addComponent(T22)
                    .addComponent(T23)
                    .addComponent(T24)
                    .addComponent(T25)
                    .addComponent(T26)
                    .addComponent(T27)
                    .addComponent(T28)
                    .addComponent(T29)
                    .addComponent(T30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T31)
                    .addComponent(T32)
                    .addComponent(T33)
                    .addComponent(T34)
                    .addComponent(T35)
                    .addComponent(T36)
                    .addComponent(T37)
                    .addComponent(T38)
                    .addComponent(T39)
                    .addComponent(T40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T41)
                    .addComponent(T42)
                    .addComponent(T43)
                    .addComponent(T44)
                    .addComponent(T45)
                    .addComponent(T46)
                    .addComponent(T47)
                    .addComponent(T48)
                    .addComponent(T49)
                    .addComponent(T50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T51)
                    .addComponent(T52)
                    .addComponent(T53)
                    .addComponent(T54)
                    .addComponent(T55)
                    .addComponent(T56)
                    .addComponent(T57)
                    .addComponent(T58)
                    .addComponent(T59)
                    .addComponent(T60))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T61)
                    .addComponent(T62)
                    .addComponent(T63)
                    .addComponent(T64)
                    .addComponent(T65)
                    .addComponent(T66)
                    .addComponent(T67)
                    .addComponent(T68)
                    .addComponent(T69)
                    .addComponent(T70))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T71)
                    .addComponent(T72)
                    .addComponent(T73)
                    .addComponent(T74)
                    .addComponent(T75)
                    .addComponent(T76)
                    .addComponent(T77)
                    .addComponent(T78)
                    .addComponent(T79)
                    .addComponent(T80))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T81)
                    .addComponent(T82)
                    .addComponent(T83)
                    .addComponent(T84)
                    .addComponent(T85)
                    .addComponent(T86)
                    .addComponent(T87)
                    .addComponent(T88)
                    .addComponent(T89)
                    .addComponent(T90))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T91)
                    .addComponent(T92)
                    .addComponent(T93)
                    .addComponent(T94)
                    .addComponent(T95)
                    .addComponent(T96)
                    .addComponent(T97)
                    .addComponent(T98)
                    .addComponent(T99)
                    .addComponent(T100)))
        );

        btnMezclar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/mezclar.png"))); // NOI18N
        btnMezclar.setToolTipText("");
        btnMezclar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMezclarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(148, 1, 1));
        jButton1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setText("Salir");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Puntuacion.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(35, 35, 35));

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(177, 217, 72));
        jLabel6.setText("Jugador 1:");

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(177, 217, 72));
        jLabel7.setText("Jugador 2:");

        jLabel8.setFont(new java.awt.Font("Cantarell", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(177, 217, 72));
        jLabel8.setText("Jugador 3:");

        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(177, 217, 72));
        jLabel9.setText("Jugador 4:");

        J1.setFont(new java.awt.Font("Cantarell", 1, 20)); // NOI18N
        J1.setForeground(new java.awt.Color(177, 217, 72));

        J2.setFont(new java.awt.Font("Cantarell", 1, 20)); // NOI18N
        J2.setForeground(new java.awt.Color(177, 217, 72));

        J3.setFont(new java.awt.Font("Cantarell", 1, 20)); // NOI18N
        J3.setForeground(new java.awt.Color(177, 217, 72));

        J4.setFont(new java.awt.Font("Cantarell", 1, 20)); // NOI18N
        J4.setForeground(new java.awt.Color(177, 217, 72));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(J1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(J2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(J3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(J4)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(J1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(J2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(J3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(J4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnMezclar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(86, 86, 86))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMezclar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMezclarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMezclarActionPerformed
        numeros.clear();
        asignarTarjetas();
        for (JLabel label : labels) {
            label.setEnabled(false);
        }
    }//GEN-LAST:event_btnMezclarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void asignarTarjetas() {
        for (int i = 0; i < 100; i++) {
            labels.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/" + ((numeros.get(i) % 25) + 1) + ".png")));
        }
    }

    private void crearEventos() {
        for (JLabel label : labels) {
            label.addMouseListener(this);
        }
    }

    @Override
    public void mouseClicked(MouseEvent evento) {
        int indice = labels.indexOf(((JLabel) evento.getSource()));
        try {
            InetAddress ip = conexion.getSocket().getInetAddress();
            int puerto = conexion.getSocket().getPort();

            socket = new Socket(ip, puerto);
            
            DataOutputStream out = new DataOutputStream(socket.getOutputStream());
            out.writeUTF(String.valueOf(indice));
            System.out.println(miIp);
            socket.close();

        } catch (UnknownHostException e) {
            System.out.println("Sock:" + e.getMessage());
        } catch (EOFException e) {
            System.out.println("EOF:" + e.getMessage());
        } catch (IOException e) {
            System.out.println("IO:" + e.getMessage());
        }

//        if (evento.getSource().getClass() == JLabel.class) {
//            voltearTarjeta(indice,miIp);
//        }
    }

    public void voltearTarjeta(int indice, String turno) {
        
        JLabel tarjeta = labels.get(indice);
        if (!tarjeta.isEnabled()) {
            tarjeta.setEnabled(true);
            seleccionados.add(tarjeta);
//                int num = labels.indexOf(((JLabel)evento.getSource()));
//                JOptionPane.showMessageDialog(null, num);
            if (seleccionados.size() == 2) {
                verificar();
            }
        }    
        
    }

    private void verificar() {
        if (seleccionados.get(0).getIcon().toString().equals(seleccionados.get(1).getIcon().toString())) {
            for (int i = 0; i < 2; i++) {
                seleccionados.get(i).setEnabled(true);
            }
            seleccionados.clear();
        } else {
            ocultar();
            seleccionados.clear();
        }
    }

    private void ocultar() {
        try {
            Thread.sleep(2000);
            for (JLabel label : seleccionados) {
                label.setEnabled(false);
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void iniciarMulticast() {
        ClienteMulticast cliente = new ClienteMulticast();
        cliente.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Panel.getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel J1;
    private javax.swing.JLabel J2;
    private javax.swing.JLabel J3;
    private javax.swing.JLabel J4;
    public javax.swing.JLabel T1;
    public javax.swing.JLabel T10;
    public javax.swing.JLabel T100;
    public javax.swing.JLabel T11;
    public javax.swing.JLabel T12;
    public javax.swing.JLabel T13;
    public javax.swing.JLabel T14;
    public javax.swing.JLabel T15;
    public javax.swing.JLabel T16;
    public javax.swing.JLabel T17;
    public javax.swing.JLabel T18;
    public javax.swing.JLabel T19;
    public javax.swing.JLabel T2;
    public javax.swing.JLabel T20;
    public javax.swing.JLabel T21;
    public javax.swing.JLabel T22;
    public javax.swing.JLabel T23;
    public javax.swing.JLabel T24;
    public javax.swing.JLabel T25;
    public javax.swing.JLabel T26;
    public javax.swing.JLabel T27;
    public javax.swing.JLabel T28;
    public javax.swing.JLabel T29;
    public javax.swing.JLabel T3;
    public javax.swing.JLabel T30;
    public javax.swing.JLabel T31;
    public javax.swing.JLabel T32;
    public javax.swing.JLabel T33;
    public javax.swing.JLabel T34;
    public javax.swing.JLabel T35;
    public javax.swing.JLabel T36;
    public javax.swing.JLabel T37;
    public javax.swing.JLabel T38;
    public javax.swing.JLabel T39;
    public javax.swing.JLabel T4;
    public javax.swing.JLabel T40;
    public javax.swing.JLabel T41;
    public javax.swing.JLabel T42;
    public javax.swing.JLabel T43;
    public javax.swing.JLabel T44;
    public javax.swing.JLabel T45;
    public javax.swing.JLabel T46;
    public javax.swing.JLabel T47;
    public javax.swing.JLabel T48;
    public javax.swing.JLabel T49;
    public javax.swing.JLabel T5;
    public javax.swing.JLabel T50;
    public javax.swing.JLabel T51;
    public javax.swing.JLabel T52;
    public javax.swing.JLabel T53;
    public javax.swing.JLabel T54;
    public javax.swing.JLabel T55;
    public javax.swing.JLabel T56;
    public javax.swing.JLabel T57;
    public javax.swing.JLabel T58;
    public javax.swing.JLabel T59;
    public javax.swing.JLabel T6;
    public javax.swing.JLabel T60;
    public javax.swing.JLabel T61;
    public javax.swing.JLabel T62;
    public javax.swing.JLabel T63;
    public javax.swing.JLabel T64;
    public javax.swing.JLabel T65;
    public javax.swing.JLabel T66;
    public javax.swing.JLabel T67;
    public javax.swing.JLabel T68;
    public javax.swing.JLabel T69;
    public javax.swing.JLabel T7;
    public javax.swing.JLabel T70;
    public javax.swing.JLabel T71;
    public javax.swing.JLabel T72;
    public javax.swing.JLabel T73;
    public javax.swing.JLabel T74;
    public javax.swing.JLabel T75;
    public javax.swing.JLabel T76;
    public javax.swing.JLabel T77;
    public javax.swing.JLabel T78;
    public javax.swing.JLabel T79;
    public javax.swing.JLabel T8;
    public javax.swing.JLabel T80;
    public javax.swing.JLabel T81;
    public javax.swing.JLabel T82;
    public javax.swing.JLabel T83;
    public javax.swing.JLabel T84;
    public javax.swing.JLabel T85;
    public javax.swing.JLabel T86;
    public javax.swing.JLabel T87;
    public javax.swing.JLabel T88;
    public javax.swing.JLabel T89;
    public javax.swing.JLabel T9;
    public javax.swing.JLabel T90;
    public javax.swing.JLabel T91;
    public javax.swing.JLabel T92;
    public javax.swing.JLabel T93;
    public javax.swing.JLabel T94;
    public javax.swing.JLabel T95;
    public javax.swing.JLabel T96;
    public javax.swing.JLabel T97;
    public javax.swing.JLabel T98;
    public javax.swing.JLabel T99;
    private javax.swing.JButton btnMezclar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mousePressed(MouseEvent me) {
    }

    @Override
    public void mouseReleased(MouseEvent me) {
    }

    @Override
    public void mouseEntered(MouseEvent me) {
    }

    @Override
    public void mouseExited(MouseEvent me) {
    }
}
